### ISSUE TITLE
Toeplitz time domain deconvolution doesn't work

### ISSUE THREAD

**Issue by Flavio9** [trichter/toeplitz#1]
Hi,
I have installed the package Toeplitz from the Anaconda prompt for Python 3.7.0 and i'm having some issues. 
After having downloaded the fortran compiler mingw-w64 for my 64-bit machine, and added the corresponding \bin to the Path environment variable, I run `f2py -c -m toeplitz toeplitz.f90` and a new file with the .pyd extension was created. 
When i run `rf-runtests` it says `c:\users\utente\anaconda3\lib\site-packages\rf\deconvolve.py:15: UserWarning: Toeplitz import error. Time domain deconvolution will not work.` followed by a list of errors.
If I try to import the .pyd file from the console it says `DLL load failed: %1 is not a valid Win32 application`.
Any suggestions on how to solve this?
Thank you,
 Flavio

**Comment by trichter** [comment]
Hi Flavio,

I am not on windows, so I cannot help with all details. Your errors sound as if there is some mixing between system and anaconda components. I recommend install toeplitz with pip inside a conda environment.

This minimal conda example is working for me:
```
conda create -n testenv python scipy
conda activate testenv
pip install toeplitz
toeplitz-runtests
```

Here is a way to install `rf` inside a conda environment (with obspyh5 enabled)

```
conda config --add channels conda-forge
conda create -n rf obspy cartopy shapely tqdm geographiclib scipy cython h5py
conda activate rf
pip install obspyh5 rf
rf-runtests
```

I hope it helps!

**Comment by trichter** [comment]
No feedback for a while. I updated the installation instructions in the readme. You need to install the FORTRAN compiler on Windows yourself.
