### ISSUE TITLE
Shape of input matrix in ctg_sl function

### ISSUE THREAD

**Issue by arndz** [trichter/toeplitz#7]
Hello,

i think there is a bug in the shape of the input matrix of the ctg_sl function.
We have a matrix B of shape (M* L, M*L) in block-toeplitz form, the matrix B consists of blocks B_i and B_-i with i=0,...,L-1 and each block has shape (M*M).

For the ctg_sl function, we need the blocks from the first row and first column as input and we can leave out the duplicate of block B_0, therefore, we have the following as input:

- Blocks from the first row (with first block B_0): B_0, B_1, B_2,..., B_L-1
- Blocks from first column (without first block B_0): B_-1, B_-2, ..., B_-L+1

Concatenating these blocks horizontally, ends up in a matrix of shape (M*M, 2*L-1) as also described in the documentation (p. 36/37). 
Documentation: https://digital.library.unt.edu/ark:/67531/metadc283582/m2/1/high_res_d/metadc283582.pdf

But.. in src/toeplitz.pyf #L90 the input matrix A must be in shape of (M*L, 2 * L - 1) and not of shape (M*M, 2*L-1).

**Comment by trichter** [comment]
Hi,

thanks for raising this issue and for the explanation. I think you are right. Additionally, I skimmed through `src/toeplitz.pyf` and found other errors, too. `x` often does have wrong shape. Also, I found a new version of `toeplitz.f90`. Therefore, at some later point, I am going to recreate the wrapper.

In the meantime, you can change the source in your local copy or create a pull request.

All relevant links:
* [John Burkhardt's website](https://web.archive.org/web/20180801221456/https://people.sc.fsu.edu/~jburkardt/f_src/toeplitz/toeplitz.html)
* [toeplitz.f90](https://web.archive.org/web/20180501171145/http://people.sc.fsu.edu/~jburkardt/f_src/toeplitz/toeplitz.f90)
* [user guide](https://digital.library.unt.edu/ark:/67531/metadc283582/)
